name: ServerTap
main: io.servertap.PluginEntrypoint
version: 0.2.1-SNAPSHOT
description: ServerTap is a REST API for Bukkit/Spigot/PaperMC Minecraft servers.
authors: [phybros, ATechAdventurer, c1oneman, Earlh21, Scarsz, au5ton, Aberdeener, Hedlund01, matteoturini, Diddyy]
load: STARTUP
website: https://servertap.io
api-version: 1.14
softdepend:
  - Vault
  - PlaceholderAPI
