---
name: Publish docs via GitHub Pages

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docs.yaml"
      - "mkdocs.yaml"
      - "docs/**"

jobs:
  publish-docs:
    runs-on: ubuntu-20.04
    if: github.event.pull_request.head.repo.fork == false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: |
          pip install \
            mkdocs>=1.1 \
            mkdocs-macros-plugin >=0.5 \
            mkdocs-material >=1.0 \
            mkdocs-minify-plugin>=0.3 \
            mkdocs-redirects>=1.0
      - run: mkdocs gh-deploy --config-file ./mkdocs.yml --force
